from .views_account import doctor_info, doctor_info_ajax, login, logout, signup, user_info, user_info_ajax
from .views_analysis import analysis_graph_search, analysis_view, deepseek_ask
from .views_consultation import (
    alter_info,
    delete_question,
    delete_reply,
    feedback,
    question,
    question_reply_ajax,
    renz,
    reply,
    wenyi,
    wenyi_reply_ajax,
)
from .views_diagnosis import smart_diagnosis
from .views_search import (
    autocomplete_api,
    department_ajax,
    department_html,
    disease_info,
    drug_info,
    index,
    info_brief_ajax,
    population_ajax,
    population_html,
    search,
    search_more,
    symptom_info,
    wenda,
    wenda_ajax,
)

__all__ = [
    'alter_info',
    'analysis_graph_search',
    'analysis_view',
    'autocomplete_api',
    'deepseek_ask',
    'delete_question',
    'delete_reply',
    'department_ajax',
    'department_html',
    'disease_info',
    'doctor_info',
    'doctor_info_ajax',
    'drug_info',
    'feedback',
    'index',
    'info_brief_ajax',
    'login',
    'logout',
    'population_ajax',
    'population_html',
    'question',
    'question_reply_ajax',
    'renz',
    'reply',
    'search',
    'search_more',
    'signup',
    'smart_diagnosis',
    'symptom_info',
    'user_info',
    'user_info_ajax',
    'wenda',
    'wenda_ajax',
    'wenyi',
    'wenyi_reply_ajax',
]
