"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x38c*)vslk#kgdocqc5pbo&adqkd-w7ri3a_#xge@f38q*!+im'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # <--- 必须放在第一行！
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wenda.apps.WendaConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wenda',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

JAZZMIN_SETTINGS = {
    # 网站标题
    "site_title": "医疗决策系统",
    "site_header": "医疗系统后台",
    "site_brand": "辅助决策平台",

    # 欢迎语
    "welcome_sign": "欢迎管理员登录医疗控制台",
    "copyright": "2026 基层医疗辅助决策平台",

    # 侧边栏设置
    "show_sidebar": True,
    "navigation_expanded": True,

    # 顶部搜索框：可以直接搜医生名字
    "search_model": "wenda.Doctor",

    # 图标设置 (让界面更生动)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",  # 管理员
        "auth.Group": "fas fa-users",

        # 你的业务模型图标
        "wenda.Doctor": "fas fa-user-md",  # 医生图标
        "wenda.User": "fas fa-procedures",  # 病人图标
        "wenda.Question": "fas fa-question-circle",  # 问号
        "wenda.Reply": "fas fa-comment-medical",  # 医疗评论
        "wenda.Feedback": "fas fa-envelope-open-text",  # 反馈
    },

    # 这里的顺序决定侧边栏的排序
    "order_with_respect_to": ["wenda", "auth"],
}

# Jazzmin 界面风格微调 (医疗蓝专业版)
JAZZMIN_UI_TWEAKS = {
    # 1. 主题选择：flatly 是最干净、最现代的扁平化主题
    "theme": "flatly",

    # 2. 顶部导航栏：使用深蓝色 (primary)，文字白色 (navbar-dark)
    "navbar": "navbar-dark bg-primary",

    # 3. 侧边栏：使用深色背景，保持沉稳
    "sidebar": "sidebar-dark-primary",

    # 4. 左上角 Logo 区域：也用深蓝色，与顶部融为一体
    "brand_colour": "navbar-primary",

    # 5. 其它细节
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}