"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x38c*)vslk#kgdocqc5pbo&adqkd-w7ri3a_#xge@f38q*!+im'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # <--- 必须放在第一行！
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wenda.apps.WendaConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'wenda.context_processors.admin_dashboard_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wenda',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

JAZZMIN_SETTINGS = {
    # 网站标题
    "site_title": "医疗中控台",
    "site_header": "智慧医疗中控台",
    "site_brand": "Medical Control",
    "site_logo": "wenda/images/wenda.png",
    "site_logo_classes": "img-circle elevation-2",
    "site_icon": "wenda/images/wenda.png",
    "login_logo": "wenda/images/wenda.png",
    "login_logo_dark": "wenda/images/wenda.png",

    # 欢迎语
    "welcome_sign": "欢迎进入临床数据与问答运营后台",
    "copyright": "2026 基层智慧医疗辅助决策平台",

    # 侧边栏设置
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,

    # 顶部搜索框：可以直接搜医生名字
    "search_model": "wenda.Doctor",
    "custom_css": "wenda/css/admin-theme.css",

    # 图标设置 (让界面更生动)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",  # 管理员
        "auth.Group": "fas fa-users",

        # 你的业务模型图标
        "wenda.Doctor": "fas fa-user-md",  # 医生图标
        "wenda.User": "fas fa-procedures",  # 病人图标
        "wenda.Question": "fas fa-question-circle",  # 问号
        "wenda.Reply": "fas fa-comment-medical",  # 医疗评论
        "wenda.Feedback": "fas fa-envelope-open-text",  # 反馈
    },

    # 这里的顺序决定侧边栏的排序
    "order_with_respect_to": ["wenda", "auth"],
    "topmenu_links": [
        {"name": "工作台", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "wenda.Doctor"},
        {"model": "wenda.Question"},
        {"model": "wenda.Feedback"},
    ],
}

# Jazzmin 界面风格微调 (医疗蓝专业版)
JAZZMIN_UI_TWEAKS = {
    "theme": "minty",
    "dark_mode_theme": None,
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-navy",
    "accent": "accent-info",
    "navbar_small_text": False,
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "button_classes": {
        "primary": "btn-info",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "custom_css": "wenda/css/admin_custom.css",
}
