# Generated by Django 3.0.4 on 2024-11-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('mail', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('birth', models.DateField(blank=True, max_length=32, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('confirmed', models.IntegerField(default=False)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('certificate', models.CharField(blank=True, max_length=64, null=True)),
                ('hospital_region', models.CharField(blank=True, max_length=64, null=True)),
                ('hospital', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=20000)),
                ('contact', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user_role', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('mail', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=16)),
                ('birth', models.DateField(blank=True, max_length=32, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wenda.Doctor')),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wenda.Question')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wenda.User'),
        ),
    ]
